[2023-03-17 21:00:28,856] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:00:28,866] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:00:28,867] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:00:28,867] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-17 21:00:28,868] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:00:28,915] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): cruzar_base2_datamunicipios> on 2023-03-17 20:00:00+00:00
[2023-03-17 21:00:28,921] {standard_task_runner.py:52} INFO - Started process 4557 to run task
[2023-03-17 21:00:28,925] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'cruzar_base2_datamunicipios', 'scheduled__2023-03-17T20:00:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmp4j_v7ax4', '--error-file', '/tmp/tmpldan1f15']
[2023-03-17 21:00:28,926] {standard_task_runner.py:80} INFO - Job 244: Subtask cruzar_base2_datamunicipios
[2023-03-17 21:00:29,011] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 21:00:29,185] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=cruzar_base2_datamunicipios
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T20:00:00+00:00
[2023-03-17 21:00:29,274] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reto_tecnico_everst.py", line 104, in cruzar_base2_datamunicipios
    df_base_3 = pd.merge(left=df_base_2, right=df_dt_mun, how='left', on=['ides', 'idmun']) #pd.merge(left=df_base_2, right=df_dt_mun, left_on='nmun', right_on='nmun')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 699, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1096, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 1779, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'ides'
[2023-03-17 21:00:29,292] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reto_tecnico_everst, task_id=cruzar_base2_datamunicipios, execution_date=20230317T200000, start_date=20230317T210028, end_date=20230317T210029
[2023-03-17 21:00:29,331] {standard_task_runner.py:97} ERROR - Failed to execute job 244 for task cruzar_base2_datamunicipios ('ides'; 4557)
[2023-03-17 21:00:29,378] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-17 21:00:29,474] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-17 21:05:29,992] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:05:30,003] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:05:30,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:05:30,005] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-17 21:05:30,005] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:05:30,093] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): cruzar_base2_datamunicipios> on 2023-03-17 20:00:00+00:00
[2023-03-17 21:05:30,101] {standard_task_runner.py:52} INFO - Started process 4684 to run task
[2023-03-17 21:05:30,105] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'cruzar_base2_datamunicipios', 'scheduled__2023-03-17T20:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmpwmsqdfly', '--error-file', '/tmp/tmpkb17t95l']
[2023-03-17 21:05:30,106] {standard_task_runner.py:80} INFO - Job 252: Subtask cruzar_base2_datamunicipios
[2023-03-17 21:05:30,194] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.cruzar_base2_datamunicipios scheduled__2023-03-17T20:00:00+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 21:05:30,388] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=cruzar_base2_datamunicipios
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T20:00:00+00:00
[2023-03-17 21:05:30,649] {reto_tecnico_everst.py:104} INFO - Guardando la base del cruce de data_municipios y base_02 en formato parquet, path: dags/data/Analytics/base_3/History/base_3_20230317_21.05.parquet
[2023-03-17 21:05:30,679] {python.py:173} INFO - Done. Returned value was: None
[2023-03-17 21:05:30,693] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reto_tecnico_everst, task_id=cruzar_base2_datamunicipios, execution_date=20230317T200000, start_date=20230317T210529, end_date=20230317T210530
[2023-03-17 21:05:30,840] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-17 21:05:30,991] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
